changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - type:breaking-change
    - title: New Features 🎉
      labels:
        - type:feat
    - title: Bugs 🐛
      labels:
        - type:bug
    - title: Other Changes
      labels:
        - "*"