name: Deploy Docs Preview

defaults:
    run:
        shell: zsh -l {0}
on:
    workflow_dispatch:
    pull_request:
        paths:
            - 'docs/**'

jobs:
    deploy-docs-preview:
        runs-on: [self-hosted, macos]
        steps:
            - uses: actions/checkout@v2
            - name: Run Docs Deploy Preview
              run: |
                  yarn docs-deploy-preview
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            - name: Add comment
              uses: actions/github-script@v6
              with:
                script: |
                    github.rest.issues.createComment({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: '✅ Preview: https://flexn-flexn-dev-flexn.vercel.app'
                    })
